python make_multialigned_fa_from_snp_ref.py Athaliana_SNPs/quality_variant_108_TAIR10_Chr1.txt > multialigned.fa
python make_multialigned_fa_from_snp_ref.py Athaliana_SNPs/quality_variant_139_TAIR10_Chr1.txt >> multialigned.fa
python make_multialigned_fa_from_snp_ref.py Athaliana_SNPs/quality_variant_159_TAIR10_Chr1.txt >> multialigned.fa
python make_multialigned_fa_from_snp_ref.py Athaliana_SNPs/quality_variant_265_TAIR10_Chr1.txt >> multialigned.fa
python make_multialigned_fa_from_snp_ref.py Athaliana_SNPs/quality_variant_350_TAIR10_Chr1.txt >> multialigned.fa

